spring.application.name=MediaFlow API
#Postgres
spring.jpa.hibernate.ddl-auto=none

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

# Path del endpoint GraphQL
spring.graphql.path=/graphql

# Habilitar impresión del schema
spring.graphql.schema.printer.enabled=true

# Ubicación del schema
spring.graphql.schema.locations=classpath:graphql/

# Habilitar introspección (permite ver el schema completo)
spring.graphql.schema.introspection.enabled=true

# ===================================
# CORS PARA GRAPHQL
# ===================================
spring.graphql.cors.allowed-origins=*
spring.graphql.cors.allowed-methods=GET,POST,OPTIONS
spring.graphql.cors.allowed-headers=*
spring.graphql.cors.allow-credentials=true
# ===================================
# LOGGING PARA DEBUGGING
# ===================================
logging.level.org.springframework.graphql=DEBUG
logging.level.graphql=DEBUG
logging.level.com.mediaflow.api=DEBUG
# SERVER CONFIGURATION
server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param
server.error.include-exception=true
#eureka
eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka